# Assignment 25 Solutions

#### Q1. What is the distinction between a numpy array and a pandas data frame? Is there a way to convert between the two if there is ?
**Ans:** NumPy arrays are geared towards numerical computations and array manipulation, while Pandas DataFrames provide enhanced data manipulation capabilities and support for heterogeneous data. 

In [1]:
# the conversion between a NumPy array and a Pandas DataFrame:
import numpy as np
import pandas as pd

# Create a NumPy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert NumPy array to DataFrame
dataframe = pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])

# Display the DataFrame
print("DataFrame:")
print(dataframe)

# Convert DataFrame to NumPy array
numpy_array = dataframe.values

# Display the NumPy array
print("NumPy array:")
print(numpy_array)


DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Q2. Identify some of the plotting techniques that are used to produce a stock-market chart ?
**Ans:** To visualize stock market data in Python, various chart types can be used. Commonly used charts include line charts, candlestick charts, volume charts, moving average charts, Bollinger Bands charts, RSI charts, and MACD charts. These charts help represent price movements, trends, volatility, trading volume, and technical indicators. Different chart types provide different insights into the data, allowing for analysis and decision-making in the stock market.

#### Q3. Why is it essential to print a legend on a stock market chart ?
**Ans:** Including a legend on a stock market chart is essential as it provides clarity, context, and interpretation of the information presented. A legend helps identify different elements or lines on the chart, allowing viewers to understand what each represents. It aids in interpreting trends, comparing data series, and analyzing performance. A legend enhances clarity, eliminates confusion, and improves communication when sharing or presenting the chart.

#### Q4. What is the best way to limit the length of a pandas data frame to less than a year ?
**Ans:** : To limit the length of a Pandas DataFrame to less than a year, you can filter the DataFrame based on the desired time range.

In [ ]:
import pandas as pd

# Assuming 'df' is your original DataFrame with a 'date' column

# Convert the 'date' column to a datetime data type
df['date'] = pd.to_datetime(df['date'])

# Set the start and end dates for the desired time range
start_date = pd.Timestamp('2022-01-01')
end_date = pd.Timestamp('2022-12-31')

# Filter the DataFrame based on the time range
filtered_df = df[(df['date'] >= start_date) & (df['date'] <= end_date)]

# Print the resulting filtered DataFrame
print(filtered_df)

#### Q5. What is the definition of a 180-day moving average ?
**Ans:** : A 180-day moving average is a type of technical analysis indicator used in finance and investing. It is calculated by taking the average value of a specific financial metric, such as a stock's closing price, over the past 180 trading days.